# -*- coding: utf-8 -*-
"""Sentiment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p4o8kxn2-IQyL-tL3OBeR6RxB0TlaQok
"""

#instalação antes de exucar o codigo abaixo!

##################################
## Sys de satistação do cliente ##
##################################

#pacote de implemetantação da máquina preditiva
import streamlit as st
# Pacote de PLN - NLTK - Natural lenguage Tool Kit
import nltk

# Titulo do Sistema
st.write("# Analise de Satisfação do Cliente")

#entrada de dados - aonde o cliente coloca seu feedback!
botao_input = st.text_input("Digite sua avaliação  : ")


#Criação da Máquina Preditiva de Satisfação do Cliente
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')
satisfacao = SentimentIntensityAnalyzer() 
pontuacao = satisfacao.polarity_scores(botao_input)

#refinamento
if pontuacao == 0:
   st.write("### Analise Neutra")

elif pontuacao["neg"] != 0:
  st.write("### Analise Negativo")

elif pontuacao["pos"] != 0:
  st.write("### Analise Positivo")


  #usar streamlit run sentiment